"""
main.py — FastAPI Application Entry Point (Phase 2)

This file creates the FastAPI app and mounts all routers.

Startup sequence:
    1. Create all database tables (if they do not already exist).
    2. Mount routers for: health, crawl, pages.

Running the server:
    uvicorn api.main:app --reload

Interactive API docs:
    http://127.0.0.1:8000/docs   (Swagger UI — auto-generated by FastAPI)
    http://127.0.0.1:8000/redoc  (ReDoc UI)

Environment variables:
    DATABASE_URL    PostgreSQL connection string.
                    Default: postgresql://postgres:postgres@localhost:5432/crawlerdb
    SQL_ECHO        Set to "true" to log all SQL to stdout.  Default: false.
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI

from api.db.session import engine
from api.db.models import Base  # noqa: F401 — imported so metadata is populated
from api.routes.health import router as health_router
from api.routes.crawl import router as crawl_router
from api.routes.pages import router as pages_router


# ── Lifespan handler ──────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Application startup / shutdown handler.

    On startup:  Create all tables defined in api.db.models if they do not
                 already exist.  This replaces manual CREATE TABLE SQL for
                 Phase 2 (Alembic migrations come in Phase 3).
    On shutdown: Nothing to do yet (connection pool is cleaned up by SQLAlchemy).
    """
    # CREATE TABLE IF NOT EXISTS for every model that inherits from Base.
    Base.metadata.create_all(bind=engine)
    yield
    # Teardown (nothing needed in Phase 2).


# ── Application ───────────────────────────────────────────────────────────────

app = FastAPI(
    title="Distributed Web Crawler — Search Engine API",
    description=(
        "Phase 2: REST API wrapping the Phase 1 crawler. "
        "Trigger crawls, query crawled pages, and inspect crawl status."
    ),
    version="0.2.0",
    lifespan=lifespan,
)

# ── Routers ───────────────────────────────────────────────────────────────────

app.include_router(health_router)   # GET /health
app.include_router(crawl_router)    # POST /api/v1/crawl, GET /api/v1/crawl/status
app.include_router(pages_router)    # GET /api/v1/pages, GET /api/v1/pages/{id}
